// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDY-NxStU5F8DAKxxcE-YnOaAOV37nCoNU',
    appId: '1:593013696372:web:defe73e82468cb7b526e21',
    messagingSenderId: '593013696372',
    projectId: 'thonglor-ae054',
    authDomain: 'thonglor-ae054.firebaseapp.com',
    storageBucket: 'thonglor-ae054.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDV_eDDUoMnJCeKdJ5tKQW98QYG3Ffr_wQ',
    appId: '1:593013696372:android:4d889b32b2a9834d526e21',
    messagingSenderId: '593013696372',
    projectId: 'thonglor-ae054',
    storageBucket: 'thonglor-ae054.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAxlgKXaIzfhFteik2r4i6C-pNELZK6o70',
    appId: '1:593013696372:ios:a0a9512f16fa826e526e21',
    messagingSenderId: '593013696372',
    projectId: 'thonglor-ae054',
    storageBucket: 'thonglor-ae054.appspot.com',
    iosBundleId: 'com.masterung.ungconnectedapi',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAxlgKXaIzfhFteik2r4i6C-pNELZK6o70',
    appId: '1:593013696372:ios:a0a9512f16fa826e526e21',
    messagingSenderId: '593013696372',
    projectId: 'thonglor-ae054',
    storageBucket: 'thonglor-ae054.appspot.com',
    iosBundleId: 'com.masterung.ungconnectedapi',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDY-NxStU5F8DAKxxcE-YnOaAOV37nCoNU',
    appId: '1:593013696372:web:20f52f8de1fdf77d526e21',
    messagingSenderId: '593013696372',
    projectId: 'thonglor-ae054',
    authDomain: 'thonglor-ae054.firebaseapp.com',
    storageBucket: 'thonglor-ae054.appspot.com',
  );
}
